on:
  workflow_dispatch:

jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/checkout@v2
      - run: |
          git config user.name 'github-actions'
          git config user.email '/'
          git branch
          yarn
          yarn release
          git --no-pager log
          git push origin master --follow-tags
      - uses: actions/github-script@v5
        with:
          github-token: ${{secrets.PUSH_TOKEN}}
          script: |
            const tag = require("child_process").execSync("git describe").toString();
            console.log(tag);
            await github.request(`POST /repos/${{ github.repository }}/releases`, {
              tag_name: tag,
              generate_release_notes: true
            });